name: compbioML
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anndata=0.10.8
  - array-api-compat=1.7.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - contourpy=1.2.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cycler=0.12.1
  - exceptiongroup=1.2.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fonttools=4.53.0
  - freetype=2.12.1
  - get-annotations=0.1.2
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - h5py=3.11.0
  - hdf5=1.14.3
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - legacy-api-wrap=1.4
  - lerc=3.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcurl=8.8.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-base=3.9.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numba=0.59.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pillow=10.3.0
  - pip=24.0
  - pynndescent=0.5.13
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - qhull=2020.2
  - readline=8.2
  - requests=2.32.2
  - scanpy=1.10.2
  - scikit-learn=1.5.0
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=2.3.1
  - torchtriton=2.3.1
  - torchvision=0.18.1
  - tqdm=4.66.4
  - typing_extensions=4.11.0
  - tzdata=2024a
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
